version: '3.8'

services:
  sql-server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WAwi5697
    ports:
      - "3306:3306"
    container_name: mysql-server-realestate
    networks:
      - mynetwork

  api:
    build:
      context: ./
      dockerfile: dockerfile-api
    depends_on:
      - sql-server
      #- redis
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=realestate_db;User=main_user;Password=WAwi5697"
      ASPNETCORE_ENVIRONMENT: "Production"  # Set the environment to Production for migrations
    ports:
      - "5001:80"
    container_name: beverlyward-realtor-api
    networks:
      - mynetwork

  angular-app:
    build:
      context: ./
      dockerfile: dockerfile-angular
    restart: always
    ports:
      - "8080:80"
    container_name:  beverlyward-realtor-client
    networks:
      - mynetwork
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin-container
    environment:
      PMA_HOST: sql-server
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: WAwi5697
    ports:
      - "8888:80"
    networks:
      - mynetwork
    depends_on:
      - sql-server

# redis:
  # image: redis:latest
  # container_name: beverlyward-realtor-redis
  # ports:
  #  - 6379:6379
  # command: redis-server /usr/local/etc/redis/redis.conf
  # volumes:
  #  - ./redis.conf:/usr/local/etc/redis/redis.conf
networks:
  mynetwork:
