version: '3.9'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: beverlyward-realtor-api
    working_dir: /api
    volumes:
      - .:/api
    ports:
      - 5000:80
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
    command: bash -c "dotnet restore && dotnet run; tail -f /dev/null"
    depends_on:
      - sql-server
      # - redis

  sql-server:
    image: mysql:latest
    environment:
     # MYSQL_ROOT_PASSWORD: WAwi5697
     MYSQL_DATABASE: realestate_db
     MYSQL_USER: main_user
     MYSQL_PASSWORD: WAwi5697
    ports:
      - "3306:3306"
    container_name: mysql-server-2022


  angular-app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 4200:80
   
  # redis:
  #   image: redis:latest
  #   container_name: beverlyward-realtor-redis
  #   ports:
  #     - 6379:6379
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf