version: '3.8'

services:
  sql-server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WAwi5697
      MYSQL_DATABASE: realestate_db
      MYSQL_USER: main_user
      MYSQL_PASSWORD: WAwi5697
    ports:
      - "3306:3306"
    container_name: mysql-server-realestate
    networks:
      - mynetwork

  api:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    restart: always
    depends_on:
      - sql-server
      #- redis
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=realestate_db;User=main_user;Password=WAwi5697"
    ports:
      - "5000:80"
    container_name: beverlyward-realtor-api
    networks:
      - mynetwork

  angular-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    container_name:  beverlyward-realtor-client
    networks:
      - mynetwork
# redis:
  # image: redis:latest
  # container_name: beverlyward-realtor-redis
  # ports:
  #  - 6379:6379
  # command: redis-server /usr/local/etc/redis/redis.conf
  # volumes:
  #  - ./redis.conf:/usr/local/etc/redis/redis.conf
networks:
  mynetwork:
