FROM mcr.microsoft.com/dotnet/sdk:6.0.101 AS build
WORKDIR /app

COPY *.sln .
COPY . .

RUN dotnet restore
RUN dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/out .

# Copy the appsettings.json file
COPY appsettings.json .

ENTRYPOINT ["dotnet", "API.dll"]
