FROM mcr.microsoft.com/dotnet/sdk:6.0.101 AS build
WORKDIR /app

COPY *.sln .
COPY . .

RUN dotnet restore
RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "API.dll"]
